# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MeeatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeeatApp
  pod 'Firebase', '>= 2.5.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
end
